function ook_program = bf2ook(bf_program, prefix)
if nargin < 2
    prefix = 'Ook';
end
ook_elements = {'.?', '?.', '..', '!!', '.!', '!.', '!?', '?!'};
bf_elements = {'>', '<', '+', '-', ',', '.', '[', ']'};
full_ook_elements = cellfun(@(suffix)[prefix ...
    , suffix(1) ...
    , ' ' ...
    , prefix ...
    , suffix(2) ...
    , ' '  ...
    ] ...
    , ook_elements ...
    , 'UniformOutput', false ...
    );
conversion_map = makearbitrarymap(bf_elements, full_ook_elements);
program_builder = arrayfun(@(token)getarbitrarymap(conversion_map, token, '') ...
    , bf_program ...
    , 'UniformOutput', false ...
    );
ook_program = cat(2, program_builder{:});
end
