function bf_program = ook2bf(ook_program)
ook_elements = {'.?', '?.', '..', '!!', '.!', '!.', '!?', '?!'};
bf_elements = {'>', '<', '+', '-', ',', '.', '[', ']'};
conversion_map = makearbitrarymap(ook_elements, bf_elements, '');
used_indexes = ook_program == '.' ...
    | ook_program == '!' ...
    | ook_program == '?' ...
    ;
bf_program = util.map(conversion_map ...
    , cellstr(reshape(ook_program(used_indexes), 2, [])') ...
    )';
end