function bf_program = ook2bf(ook_program)
ook_elements = {'.?', '?.', '..', '!!', '.!', '!.', '!?', '?!'};
bf_elements = {'>', '<', '+', '-', ',', '.', '[', ']'};
conversion_map = makearbitrarymap(ook_elements, bf_elements);
used_indexes = ook_program == '.' ...
    | ook_program == '!' ...
    | ook_program == '?' ...
    ;
reduced_ook_program = reshape(ook_program(used_indexes), 2, [])';
reduced_ook_program = cellstr(reduced_ook_program);
%UniformOuptut has to be set to false because Octave fails to recognise single
%characters as scalar values
bf_program = cellfun(@(token)getarbitrarymap(conversion_map, token, '') ...
    , reduced_ook_program ...
    , 'UniformOutput', false ...
    );
bf_program = [bf_program{:}];
end
